import pkg from "../package.json";
import { publicBasePath } from "./config";

export const EXTENSION_VERSION: string = pkg.version;

export function downloadFile(target: "chromium" | "firefox"): string {
  return `chat-to-pdf-${target}-v${EXTENSION_VERSION}.zip`;
}

/** Served from public/downloads (generated by scripts/build-extension.mjs during `next build`). */
export function downloadHref(target: "chromium" | "firefox"): string {
  return `${publicBasePath()}/downloads/${downloadFile(target)}`;
}

export function checksumsHref(): string {
  return `${publicBasePath()}/downloads/SHA256SUMS`;
}
